name: Test

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
      
      - uses: DevExpress/testcafe-build-system/actions/build@main


  test:
    runs-on: ubuntu-latest
    needs: [build]
    environment: CI

    env:
      DISPLAY: ':99.0'
      
    steps:
      - run: |
          sudo apt install fluxbox
          Xvfb :99.0 -screen 0 1920x1080x24 &
          sleep 3
          fluxbox >/dev/null 2>&1 &

      - uses: DevExpress/testcafe-build-system/actions/prepare@main
        with:
          node-version: 'latest'

      - uses: DevExpress/testcafe-build-system/actions/test-npm@main
        with:
          task: test
